# utils/config.yml
#批量添加和修改、删除front matter配置文件

# 需要批量处理的路径，docs文件夹内的文件夹 (数组。映射路径：docs/arr[1]/arr[2] ... )
path:
  - docs # 第一个成员必须是docs
  - 02.前端
  - 08.Vite

# 要删除的字段 (数组)
# delete:  
#   - article

 # 要添加、修改front matter的数据 （front matter中没有的数据则添加，已有的数据则覆盖）
data:
  date: 2022-05-15 08:38:18
